version: '3.4'

services:
  sqlserver:
      image: mcr.microsoft.com/mssql/server:latest
      environment:
        SA_PASSWORD: "MinhaSenha!"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Developer"
      ports:
        - "1433:1433"